<html>
    <head>
        <meta charset="UTF-8"/>
        <title>De Olho No Lixo</title>
    </head>
    <body>
        <div>
            <ul>
                <li><a href="<?php echo $this->url(array('controller' => 'Empresa', 
                    'action' => 'index')); ?>">Empresa</a></li>
                <li><a href="<?php echo $this->url(array('controller' => 'PontoColeta',
                    'action' => 'index')); ?>">Ponto de coleta</a></li>
                <li><a href="<?php echo $this->url(array('controller' => 'Empresa',
                    'action' => 'buscar')) ?>">Buscar empresas</a></li>
                <li><a href="<?php echo $this->url(array('controller' => 'PontoColeta',
                    'action' => 'buscar')) ?>">Buscar pontos de coleta</a></li>
            </ul>
        </div>
       <?php echo $this->layout()->content; ?> 
    </body>
</html>