<div align="center">
<h3>Cadastre o ponto de coleta</h3>
<table>
    <tr>
        <td>
<?php 
    echo $this->form;
    echo $this->resp; 
    ?>      
        </td>
    </tr>
</table>
</div>
<style type="text/css">
    body{
        background-image: linear-gradient(#C1FFC1, #00CDCD);
    }
    input[type=text], select{
        width: 250px;
        height: 35px;
    }
    input[type=submit]{
        width: 100px;
        height: 35px;
        border-radius: 10px;
        background-image: linear-gradient(#00FA9A, #20B2AA);
        color: white;
    }
</style>